name: t5-3b
family: t5
model_path: google/t5-3b-ssm-nq
device_map:
  shared: 0
  lm_head: 1
  encoder.embed_tokens: 1
  encoder.block.0: 1
  encoder.block.1: 1
  encoder.block.2: 1
  encoder.block.3: 1
  encoder.block.4: 1
  encoder.block.5: 1
  encoder.block.6: 1
  encoder.block.7: 1
  encoder.block.8: 1
  encoder.block.9: 1
  encoder.block.10: 1
  encoder.block.11: 1
  encoder.block.12: 1
  encoder.block.13: 2
  encoder.block.14: 2
  encoder.block.15: 2
  encoder.block.16: 2
  encoder.block.17: 2
  encoder.block.18: 2
  encoder.block.19: 2
  encoder.block.20: 2
  encoder.block.21: 2
  encoder.block.22: 2
  encoder.block.23: 2
  encoder.final_layer_norm: 2
  encoder.dropout: 2
  decoder.embed_tokens: 2
  decoder.block.0: 3
  decoder.block.1: 3
  decoder.block.2: 3
  decoder.block.3: 3
  decoder.block.4: 3
  decoder.block.5: 3
  decoder.block.6: 4
  decoder.block.7: 4
  decoder.block.8: 4
  decoder.block.9: 4
  decoder.block.10: 4
  decoder.block.11: 4
  decoder.block.12: 5
  decoder.block.13: 5
  decoder.block.14: 5
  decoder.block.15: 5
  decoder.block.16: 5
  decoder.block.17: 5
  decoder.block.18: 6
  decoder.block.19: 6
  decoder.block.20: 6
  decoder.block.21: 6
  decoder.block.22: 6
  decoder.block.23: 6
  decoder.final_layer_norm: 7
  decoder.dropout: 7
generation_split: null
generation_combine: null
batch_size: 8